load("//bazel/toolchains/sass:toolchain.bzl", "define_all_toolchains")

# Defines the toolchain type for scss compiler
toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

define_all_toolchains()
