"""Creating venv based on rules_pyvenv and some things on top"""

load("@rules_pyvenv//:venv.bzl", "py_venv")

def export_devenv(name, venv_location, deps, **kwargs):
    """Uses `py_venv` and some `.pth` magic on top.

    Args:
      name: standard one
      venv_location: see py_venv(venv_location=)
      deps: see py_venv(deps=)
      **kwargs: the rest
    """

    # The name of the python binary generated by `py_venv` macro.
    py_venv_name = name + "_venv"
    py_venv(
        name = py_venv_name,
        always_link = True,
        venv_location = venv_location,
        deps = deps,
        tags = ["no-remote", "no-sandbox", "manual"],
    )

    native.sh_binary(
        name = name,
        data = [":" + py_venv_name],
        srcs = ["run.sh"],
        args = ["$(location :" + py_venv_name + ")"],
        tags = ["no-remote", "no-sandbox", "manual"],
        **kwargs
    )
